version: '3.0'

expectations:

  population_size: 50000

actions:

  extract:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
      --index-date-range '2018-01-01 to 2021-01-01 by month'
      --output-dir 'output/measures'
      --output-format feather
    needs: []
    outputs:
      highly_sensitive:
        cohort: output/measures/input*.feather

  measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition
      --output-dir=output/measures
    needs:
    - extract
    outputs:
      moderately_sensitive:
        csv: output/measures/measure_death.csv

  process_measures:
    run: r:latest analysis/process_measures.R
      --df_input output/measures/measure_death.csv
      --dir_output output/measures/
    needs:
    - measures
    outputs:
      moderately_sensitive:
        feather: output/measures/*.feather

  standardise:
    run: r:latest analysis/standardisation.R
      --df_input output/measures/measure_death.feather
      --dir_output output/standardised/
      --standardisation_strata year;sex;ageband5year;region
      --subgroups overall;ageband20year;sex;region
      --numerator death_1year
      --denominator population
      --reference_population 'ONS-England-mid-year-pop'
      --min_count 6
      --round_method mid
      --make_plot TRUE
    needs:
    - process_measures
    outputs:
      moderately_sensitive:
        feather: output/standardised/*.feather
        jpg: output/standardised/*.jpeg


  ## # # # # # # # # # # # # # # # # # # #
  ## End
  ## # # # # # # # # # # # # # # # # # # #

